// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RejectButtonsController from "./reject_buttons_controller"
application.register("reject-buttons", RejectButtonsController)

import SeeResultsController from "./see_results_controller"
application.register("see-results", SeeResultsController)

import SwipableCardsController from "./swipable_cards_controller"
application.register("swipable-cards", SwipableCardsController)
