meta_product_name: "Mamyuk"
meta_title: "Mamyuk - Your Restaurant Finder Companion"
meta_description: "We help you find a place to eat"
meta_image: "mamyuk.png" # should exist in `app/assets/images/`
